plugins:
  eslint:
    enabled: true
    channel: 'eslint-5'
    config:
      ignore_warnings: true
    checks:
      import/no-unresolved:
        enabled: false
      new-cap:
        enabled: false
ratings:
  paths:
    - '*.js'
exclude_patterns:
  - '**/build/'
  - '**/node_modules/'
  - '**/tests/'
  - '**/*.d.ts'
