engines:
  eslint:
    enabled: true
    channel: 'eslint-2'
    config:
      ignore_warnings: true
    checks:
      import/no-unresolved:
        enabled: false
      new-cap:
        enabled: false
ratings:
  paths:
  - '*.js'
